### PR TITLE
Add Addic7ed ID mapping

### PR DESCRIPTION
**Pull request by mrhotio**

### CODE REVIEW

**Comment by BenjV** [comment]
Would you please be so kind not to ask for a merge for this kind of trival changes.
If a addic7ed mapping is missing or a spelling mistake is bothering you please create n issue and I will fix it.

**Comment by hotio** [comment]
Apologies, on my clean install the mappings were missing, so....where do you see they are included?

If you prefer not to receive pull requests, you can disable that feature on GitHub. I just wanted you to save a bit of hassle for such trivial changes :-)

**Comment by BenjV** [comment]
I use GitHub just for distribution and pull request merging will mess-up my own system.

Besides the addicmappings in the code self, autosub also uses the AddicMapping.txt.
At the start of every search round autosub will check the Addicmapping.txt on GitHub to see if mappings are added.
This way I can add mappings without have to create a new release.

So I you think a mapping is missing, just create an issue for it and I will add it in.

**Comment by hotio** [comment]
Yes, I believe the mappings from the PR are missing.

**Comment by BenjV** [comment]
I have added them

**Pull request closed without merging**
